Add availability to `ConstantAsyncSequence`
We were running into build issues like this

> grpc-swift-nio-transport/Sources/GRPCNIOTransportCore/Internal/ConstantAsyncSequence.swift:37:17: error: concurrency is only available in macOS 10.15.0 or newer

when building this package on macOS. It looks like there is just a missing availability annotation.